# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{tcl}
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sam Stephenson"]
  s.date = %q{2010-12-01}
  s.description = %q{A minimal Ruby interface to libtcl}
  s.email = %q{sstephenson@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION",
    "lib/.gitignore",
    "lib/tcl.rb",
    "lib/tcl/interp.rb",
    "lib/tcl/interp_helper.rb",
    "lib/tcl/proc.rb",
    "lib/tcl/var.rb",
    "script/console",
    "tcl.gemspec",
    "test/fixtures/test.tcl",
    "test/helper.rb",
    "test/interp_receive_test.rb",
    "test/interp_test.rb",
    "test/proc_test.rb",
    "test/test_helper.rb",
    "test/var_test.rb"
  ]
  s.homepage = %q{http://github.com/sstephenson/ruby-tcl}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Tcl bindings for Ruby}
  s.test_files = [
    "test/helper.rb",
    "test/interp_receive_test.rb",
    "test/interp_test.rb",
    "test/proc_test.rb",
    "test/test_helper.rb",
    "test/var_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ffi>, ["~> 1.0.0"])
    else
      s.add_dependency(%q<ffi>, ["~> 1.0.0"])
    end
  else
    s.add_dependency(%q<ffi>, ["~> 1.0.0"])
  end
end

